ext {
    cfgs = [
            compileSdkVersion: 34,
            applicationId    : "com.ios.ioslite.odm",
            minSdkVersion    : 26,
            targetSdkVersion : 34,
            sourceCompatibility : 1.8,
            targetCompatibility : 1.8
    ]

    /*
     *  所有三方库配置；
     *  1. 避免各模块引用同一三方库的不同版本，引起编译问题；
     *  2. 库名称中不要使用通配符 “ + ”；
     */

    libs = [
            "support-v4"                 : 'androidx.legacy:legacy-support-v4:1.0.0',
            "support-v13"                : 'com.android.support:support-v13:24.2.1',
            "appcompat-v7"               : 'androidx.appcompat:appcompat:1.0.0',
            "cardview-v7"                : 'androidx.cardview:cardview:1.0.0',
            "recyclerview-v7"            : 'androidx.recyclerview:recyclerview:1.0.0',
            "palette-v7"                 : 'androidx.palette:palette:1.0.0',
            "design"                     : 'com.google.android.material:material:1.0.0',
            "annotations"                : 'com.android.support:support-annotations:23.1.1',
            "multidex"                   : "com.android.support:multidex:1.0.1",
            "support-compat"             : 'androidx.core:core:1.5.0-alpha04',
            "viewpager2"                 : 'androidx.viewpager2:viewpager2:1.0.0',
            "viewpager"                 : 'androidx.viewpager:viewpager:1.0.0',
            "constraintlayout"           : 'androidx.constraintlayout:constraintlayout:1.2.0',
            "greendao"                   : 'de.greenrobot:greendao:2.1.0',
            "gson"                       : 'com.google.code.gson:gson:2.6.2',
            "butterknife"                : 'com.jakewharton:butterknife:7.0.1',
            "leakcanary"                 : 'com.squareup.leakcanary:leakcanary-android:1.3.1',
            "glide"                      : 'com.github.bumptech.glide:glide:3.7.0',
            "glide-okhttp-integration"   : 'com.github.bumptech.glide:okhttp-integration:1.3.1',
            "okhttp"                     : 'com.squareup.okhttp3:okhttp:3.8.1',
//            "okhttp-urlconnection"       : 'com.squareup.okhttp:okhttp-urlconnection:2.7.0',
            "foldable-layout"            : 'com.alexvasilkov:foldable-layout:1.0.1',
            "etsy-grid"                  : 'com.etsy.android.grid:library:1.0.5',
            "pinyin4j"                   : 'com.belerweb:pinyin4j:2.5.1',
            "file-downloader"            : 'com.liulishuo.filedownloader:library:0.3.2',
            "firebace-core"              : 'com.google.firebase:firebase-core:10.2.1',
            "firebace-ads"               : 'com.google.firebase:firebase-ads:10.2.1',
            "firebase-messaging"         : 'com.google.firebase:firebase-messaging:10.2.1',
            "gms-play-services-ads"      : 'com.google.android.gms:play-services-ads:10.2.1',
            "gms-play-services-analytics": 'com.google.android.gms:play-services-analytics:10.2.1',
            "gms-play-services-gcm"      : 'com.google.android.gms:play-services-gcm:10.2.1',
            "image-cropper"              : 'com.theartofdev.edmodo:android-image-cropper:2.3.1',
            "umeng"                      : 'com.umeng.analytics:analytics:latest.integration',
            "roundedimageview"           : 'com.makeramen:roundedimageview:2.3.0',
            "flurry-android-analytics"   : 'com.flurry.android:analytics:6.4.2',
            "flurry-ads"                 : 'com.flurry.android:ads:6.4.2',
            "audience-network-sdk"       : 'com.facebook.android:audience-network-sdk:4.+',
            "droi-bass-core"             : 'com.droi.sdk:Core:+',
            "droi-bass-analytics"        : 'com.droi.sdk:analytics:+',
            "droi-bass-selfupdate"       : 'com.droi.sdk:selfupdate:+',
            "commons-lang"               : 'org.apache.commons:commons-lang3:3.5',
            "inmobi-ads"                 : 'com.inmobi.monetization:inmobi-ads:7.0.2',
            "droi-adzodiac"              : 'com.idroi:adzodiac:+',
            "facebook-fresco"            : 'com.facebook.fresco:fresco:1.4.0',
            "facebook-fresco-anim"       : 'com.facebook.fresco:animated-webp:0.12.0',
            "facebook-fresco-web"        : 'com.facebook.fresco:webpsupport:0.12.0',
            "facebook-fresco-img"        : 'com.facebook.fresco:imagepipeline:0.12.0',
//            "glide-okhttp3-integration"  : 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar',
    ]
}