rootProject.name = "BaseAndroid"
include ':app'
include ':library:BatterySave'
include ':library:cropper'
include ':module:iOSLauncher'
include ':library:ThemeResource:ThemeDefault'
include ':library:iosdialogs4android'
include ':library:RealTimeBlurView'
include ':library:iOSLiteCommon'
include ':module:iOSSearch'
include ':module:iOSSettings'
include ':module:iOSThemeClub'
include ':library:iOSAppsNewsProvider'
include ':library:iOSSwitchControl'
